.TH RMTRASH 1 "02 October 2016" "rmtrash 0.3.5" "BSD General Commands Manual"
.SH NAME
rmtrash \- move files to the trash
.SH SYNOPSIS
.B rmtrash
[\fB-u\fR \fIUSERNAME\fR] [\fB-f\fR] [\fB-h\fR] [\fB-v\fR] file-name [\fIfile-name\fR]
.SH DESCRIPTION
.PP
This command moves files to the trash rather than removing them totally from the file system.  Very useful if you decide you want that file after all...
.TP
\fB\-u\fR \fIUSERNAME\fR
an optional argument.  This will move the file to the specified user's trash. Note that you need sufficient privileges to accomplish this.
.TP
\fB\-f\fR
an optional argument.  This will suppress all output and ignore all errors.
.TP
\fB\-h\fR
displays a small help screen displaying these options.
.TP
\fB\-v\fR
prints out version info on \fBrmtrash\fR.
.SH BUGS
Not directly related to \fBrmtrash\fR; the trash can icon will not display that there is trash in it if it was empty and you used this command to place something there.  It will stay empty until you throw something away in the Finder.
.SH AUTHOR
Written by Darkshadow <darkshadow02@mac.com>
.br
Extended by Sebastian Keller <sebikeller@myfucking.email>
.SH COPYRIGHT
Copyright \(co 2003 Night Productions.
.br
Copyright \(co 2015-2016 Sebastian Keller.
.br
This is free software.  There is NO warranty; not even for merchantability or fitness for a particular purpose.
.SH "SEE ALSO"
.BR rm (1),
.BR rmdir (1)
